// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OverlordAPI.Data;

#nullable disable

namespace OverlordAPI.Migrations
{
    [DbContext(typeof(OverlordDbContext))]
    [Migration("20260115082304_AddSeedingData")]
    partial class AddSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinionMission", b =>
                {
                    b.Property<int>("MinionsId")
                        .HasColumnType("int");

                    b.Property<int>("MissionsId")
                        .HasColumnType("int");

                    b.HasKey("MinionsId", "MissionsId");

                    b.HasIndex("MissionsId");

                    b.ToTable("MinionMission");
                });

            modelBuilder.Entity("OverlordAPI.Models.Entities.EvilLair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Pacific Ocean",
                            Name = "Volcano Island"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Low Earth Orbit",
                            Name = "The Moon Base"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Mariana Trench",
                            Name = "Deep Sea Trench"
                        });
                });

            modelBuilder.Entity("OverlordAPI.Models.Entities.Minion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EvilLairId")
                        .HasColumnType("int");

                    b.Property<int>("EvilLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EvilLairId");

                    b.ToTable("Minions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            EvilLairId = 1,
                            EvilLevel = 8,
                            Name = "Kevin",
                            Type = "Scientist"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            EvilLairId = 1,
                            EvilLevel = 3,
                            Name = "Bob",
                            Type = "Soldier"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            EvilLairId = 2,
                            EvilLevel = 6,
                            Name = "Dave",
                            Type = "Infiltrator"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            EvilLairId = 3,
                            EvilLevel = 1,
                            Name = "Stuart",
                            Type = "Janitor"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            EvilLairId = 2,
                            EvilLevel = 9,
                            Name = "Scarlett",
                            Type = "Mystic"
                        });
                });

            modelBuilder.Entity("OverlordAPI.Models.Entities.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = 10,
                            Title = "Steal the Moon",
                            isCompleted = false
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = 1,
                            Title = "Rig the Local Bingo",
                            isCompleted = false
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = 5,
                            Title = "Replace Clouds with Cotton Candy",
                            isCompleted = false
                        });
                });

            modelBuilder.Entity("MinionMission", b =>
                {
                    b.HasOne("OverlordAPI.Models.Entities.Minion", null)
                        .WithMany()
                        .HasForeignKey("MinionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OverlordAPI.Models.Entities.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OverlordAPI.Models.Entities.Minion", b =>
                {
                    b.HasOne("OverlordAPI.Models.Entities.EvilLair", "EvilLair")
                        .WithMany("Minions")
                        .HasForeignKey("EvilLairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvilLair");
                });

            modelBuilder.Entity("OverlordAPI.Models.Entities.EvilLair", b =>
                {
                    b.Navigation("Minions");
                });
#pragma warning restore 612, 618
        }
    }
}
